import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navber from "@/components/shared/Navber";
import Footer from "@/components/shared/footer/Footer";
import Providerr from "@/components/provider/Provider";
import ShowNavber from "@/components/clientComponents/showNavber";
import 'react-phone-input-2/lib/style.css'


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// }); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body>
        <Providerr>
          <div className="mb-16">
            <ShowNavber></ShowNavber>
          </div>
          {children}
          {/* <Footer></Footer> */}
        </Providerr>

      </body>
    </html>
  );
}
