import type { Metadata } from "next";
import "./globals.css";
import Providerr from "@/components/provider/Provider";
import ShowNavber from "@/components/clientComponents/showNavber";
import 'react-phone-input-2/lib/style.css'
import  { Toaster } from 'react-hot-toast';
import ShowFooter from "@/components/clientComponents/showFooter";




// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// }); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className="max-w-screen-2xl mx-auto">    
        <Providerr>
          <div className="relative">
            <ShowNavber></ShowNavber>
          </div>
          {children}
          <ShowFooter></ShowFooter>
          <Toaster/>
        </Providerr>
      
      </body>
    </html>
  );
}
